baseURL: "https://gr0esch.github.io/" 
title: Samuel Groesch
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: samuelgroesch

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Design
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 4     

params:
    description: "I am a Research and Teaching Associate in the Media & Internet Governance Division at the University of Zurich. <br>I hold an MSc in Data & Society from LSE and a BA in Communication & Politics from Zeppelin University."
    author: Samuel Groesch
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Samuel Groesch
          subtitle: "I am a Research and Teaching Associate in the Media & Internet Governance Division at the University of Zurich, holding an MSc in Data & Society from LSE and a BA in Communication & Politics from Zeppelin University. My research interests include platform governance, data protection and the evaluation of harmful online content, as well as computational methods."
          imageUrl: "/picture_new.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Samuel Groesch
          # buttons:
          #   - name: Papers
          #     url: /papers/
          #   - name: Courses
          #     url: /courses/
          #   - name: Design
          #     url: /design/
    socialIcons:
        # - name: CV
        #   url: "/cv.pdf"
        - name: Email
          url: "mailto:s.groesch@ikmz.uzh.ch"
        - name: CV
          url: "https://www.ikmz.uzh.ch/en/research/divisions/media-and-internet-governance/team/samuel-groesch.html"
        - name: Twitter
          url: "https://twitter.com/samuelgroesch"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/samuelgroesch/"
        - name: GitHub
          url: "https://github.com/gr0esch"



    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Samuel Groesch"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
